services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - 5173:5173

  web:
    build:
      context: ./docker/web
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - app
    volumes:
      - .:/app

  db:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    ports:
      - 5431:5432
    environment:
      - POSTGRES_DB=training
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - PGTZ=Asia/Tokyo
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  db-test:
    build:
      context: ./docker/db
      dockerfile: Dockerfile
    ports:
      - 5433:5432 #PostgreSQLはコンテナ内でデフォルトでポート 5432 を使用しているため、5433:5432 のポートマッピングが必要
    environment:
      - POSTGRES_DB=testing
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - PGTZ=Asia/Tokyo

  mail:
    image: axllent/mailpit:v1.13
    ports:
      - '8025:8025' #web上でmailサーバのGUIを表示させるポート
      - '1025:1025' #smtpサーバ
    environment:
      - MP_DATA_FILE=/data/mailpit.db # メールの内容をディスクに保存する場合のパス指定
    volumes:
      - mp-data-file:/data # 永続化する

# コンテナの動作を終了したあとでも、起動したら終了前のデータの状態を引っ張ってこられるようにしている
volumes:
  postgres-volume:
  mp-data-file:
