name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
  pull_request_review_comment:
    types: [created]

concurrency:
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: シークレットの存在確認
        run: |
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "Error: OPENAI_API_KEY is not set"
            exit 1
          fi

      - name: Code Review Step with Retry
        id: code-review
        run: |
          set +e
          max_attempts=2
          attempt=1
          while [ $attempt -le $max_attempts ]; do
            echo "Attempt $attempt of $max_attempts..."
            gh_output=$(gh workflow run coderabbitai/ai-pr-reviewer@latest 2>&1)
            exit_code=$?
            if [ $exit_code -eq 0 ]; then
              echo "Code review succeeded."
              break
            else
              echo "Code review failed. Retrying in 10 seconds..."
              attempt=$(( $attempt + 1 ))
              sleep 10
            fi
          done

          if [ $exit_code -ne 0 ]; then
            echo "Code review failed after $max_attempts attempts."
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
