name: Laravel Docker CI/CD

on: [push, pull_request]
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker containers
        run: |
          docker-compose -f ./compose.yml up -d --build

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to be ready..."
          for i in {1..30}; do
            (docker-compose -f ./compose.yml exec db pg_isready -U test -d training > /dev/null 2>&1 && echo "DB is ready" && break) || true
            echo "Waiting for DB..."
            sleep 5
          done

      - name: Install dependencies
        run: |
          docker-compose -f ./compose.yml exec app composer install

      - name: Set up environment
        run: |
          docker-compose -f ./compose.yml exec app cp .env.example .env
          docker-compose -f ./compose.yml exec app php artisan key:generate
          docker-compose -f ./compose.yml exec app php artisan migrate --force

      - name: Run tests
        run: |
          docker-compose -f ./compose.yml exec app php artisan test

      - name: Tear down Docker containers
        if: always()
        run: docker-compose -f ./compose.yml down --volumes --remove-orphans
