name: Laravel Docker CI/CD

on: [push, pull_request]
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and run Docker containers
        run: |
          docker-compose -f docker-compose.yml up -d --build

      - name: Wait for database services to be ready
        run: |
          echo "Waiting for database services to be ready..."
          for i in {1..30}; do
            (docker-compose exec db pg_isready -U test -d training > /dev/null 2>&1 && echo "Training DB is ready" && break) || true
            echo "Waiting for Training DB..."
            sleep 5
          done
          for i in {1..30}; do
            (docker-compose exec db-test pg_isready -U test -d testing > /dev/null 2>&1 && echo "Testing DB is ready" && break) || true
            echo "Waiting for Testing DB..."
            sleep 5
          done

      - name: Install dependencies
        run: |
          docker-compose exec app composer install

      - name: Set up environment
        run: |
          docker-compose exec app cp .env.testing .env
          docker-compose exec app php artisan key:generate
          docker-compose exec app php artisan migrate --force

      - name: Run tests
        run: |
          docker-compose exec app php artisan test

      - name: Tear down Docker containers
        if: always()
        run: docker-compose down --volumes --remove-orphans
