name: Laravel Docker CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: password
          POSTGRES_DB: training
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: pdo, pgsql, pdo_pgsql

      - name: composer install
        run: composer install --prefer-dist --no-progress

      - name: Copy .env
        run: cp .env.example .env

      - name: Setup .env
        run: |
          echo "APP_ENV=testing" >> .env
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=postgres" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=training" >> .env
          echo "DB_USERNAME=test" >> .env
          echo "DB_PASSWORD=password" >> .env

      - name: Check Postgres health
        run: pg_isready -h postgres -p 5432 -U test || exit 1

      - name: Generate application key
        run: php artisan key:generate

      - name: Clear config cache
        run: |
          php artisan config:clear
          php artisan cache:clear

      - name: Run migrations and seed
        run: |
          php artisan migrate --force
          php artisan db:seed --force

      - name: Run tests
        run: php artisan test --env=testing
