name: Test Postgres Setup

on:
  pull_request:

jobs:
  postgres-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: "test"
          POSTGRES_PASSWORD: "password"
          POSTGRES_DB: "training"
        ports:
          - 5432:5432
        options: >
          --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Wait for Postgres to be ready
        run: |
          for i in {1..10}; do
            if pg_isready -h postgres -p 5432 -U test; then
              echo "Postgres is ready"
              exit 0
            fi
            echo "Waiting for Postgres..."
            sleep 5
          done
          echo "Postgres did not become ready in time"
          exit 1
