name: Run Tests

on: [push, pull_request]
# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testing
        options: >-
          --health-cmd "pg_isready -U github -d test_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # Adjust to your required PHP version
          extensions: pdo, pdo_pgsql
          ini-values: "post_max_size=512M"
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Set up environment file
        env:
          DB_CONNECTION: pgsql
          DB_HOST: db-test
          DB_PORT: 5432
          DB_DATABASE: testing
          DB_USERNAME: test
          DB_PASSWORD: password
        run: |
          cp .env.testing .env
          php artisan key:generate

      - name: Run database migrations
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test
