name: Testing Laravel with PostgreSQL

on: [push, pull_request]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: 'postgres'
          POSTGRES_PASSWORD: 'postgres'
          POSTGRES_DB: 'laravel_testing'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, intl, pgsql

    - name: Set up .env file
      run: |
        echo "APP_ENV=testing" >> .env
        echo "APP_DEBUG=true" >> .env
        echo "APP_KEY=" >> .env
        echo "DB_CONNECTION=${{ secrets.DB_CONNECTION }}" >> .env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
        echo "DB_DATABASE=${{ secrets.DB_DATABASE }}" >> .env
        echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

    - name: Debug .env file
      run: cat .env

    - name: Wait for PostgreSQL
      run: |
        echo "Waiting for PostgreSQL to be ready..."
        for i in {1..30}; do
          pg_isready -h db -p 5432 -U postgres && echo "PostgreSQL is ready!" && break
          echo "PostgreSQL is not ready, retrying in 1 second..."
          sleep 1
        done

    - name: Verify PostgreSQL connection with psql
      run: |
        PGPASSWORD=postgres psql -h db -U postgres -d laravel_testing -c "SELECT 1"

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Debug Composer Install
      run: composer install --prefer-dist --no-progress || cat composer.lock

    - name: Generate key
      run: php artisan key:generate

    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Execute Migration & Seed
      run: php artisan migrate:refresh --seed --force

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit
