name: Lint And Static Analyse

on:
  pull_request:

jobs:
  pint-and-larastan-analyse:
    name: pint-and-larastan-analyse
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
      - name: Install Pint
        run: composer require laravel/pint
      - name: Run Pint
        run: ./vendor/bin/pint --test
      - name: Install Larastan
        run: composer require larastan/larastan:^2.0
      - name: Run Larastan
        run: ./vendor/bin/phpstan analyse -c phpstan.neon --error-format=raw --no-progress